package com.equities.equityplatform.model;

import com.equities.equityplatform.util.PasswordUtil;

import static com.equities.equityplatform.util.PasswordUtil.hashPassword;

public class Login {

    private Integer loginId;        // Optional, auto-generated by DB
    private int userId;         // Foreign key to `users` table
    private String passwordHash;

    // Constructors
    public Login() { }

    // Constructor for creating new login (hashes password)
    public Login(Integer loginId, String passwordHash) {
        this.loginId = loginId;
        this.passwordHash = PasswordUtil.hashPassword(passwordHash);
    }

    // Constructor for database retrieval (password already hashed)
    public Login(Integer loginId, int userId, String hashedPassword) {
        this.loginId = loginId;
        this.userId = userId;
        this.passwordHash = hashedPassword;
    }

    // Getters and Setters
    public Integer getLoginId() {
        return loginId;
    }
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    public int getUserId() {
        return userId;
    }
    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getPasswordHash() {
        return passwordHash;
    }
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
}