package com.equities.equityplatform.model;

import com.equities.equityplatform.util.PasswordUtil;

import static com.equities.equityplatform.util.PasswordUtil.hashPassword;

public class Login {

    private int loginId;        // Optional, auto-generated by DB
    private int userId;         // Foreign key to `users` table
    private String passwordHash;

    // Constructors
    public Login() {}

    public Login(int userId, String passwordHash) {
        this.userId = userId;
        this.passwordHash = PasswordUtil.hashPassword(passwordHash);
    }

    // Getters and Setters
    public int getLoginId() {
        return loginId;
    }
    public void setLoginId(int loginId) {
        this.loginId = loginId;
    }

    public int getUserId() {
        return userId;
    }
    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getPasswordHash() {
        return passwordHash;
    }
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
}